# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  node: circleci/node@21.6.1
jobs:
  test:
    docker:
      - image: cimg/node:21.6.1-browser
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
  build:
    docker:
      - image: cimg/node:21.6.1-browser
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/node:21.6.1-browser
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  default:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
