name: Cypress Specs

on:
  push:
    branches:
      - feature/df-49-cicd-vercel
  pull_request:
    branches:
      - feature/df-49-cicd-vercel


jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start